name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main  # or your main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3

      - name: Upload static site to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"                     # Your index.html is in the root
          api_location: "api"                   # If you have Azure Functions
          output_location: ""                  # Not needed if no build step
